### ISSUE TITLE
wikiに書いてある仕様と実際のゲームの仕様の差異の洗い出し

### ISSUE THREAD

**Issue by phb2** [hikky-coop/rpg#11]
ひきぷろ氏が途中でプロジェクトから抜けた段階からひきねこ（phb2）が脳内ドキュメントでゲームの拡張を続けていました。
その仕様については文書化しておらず、ひきぷろ氏が考えてくれたwikiの仕様とは異なる点が多くあります。

**Comment by phb2** [comment]
phb2が担当します。

**Comment by phb2** [comment]
プルリクエスト対応で疲れてしまったのでインターバルを置いて取り組みます。

**Comment by phb2** [comment]
https://github.com/hikky-coop/rpg/wiki で取り組み。

**Comment by phb2** [comment]
疲れてしまったので休憩。

**Comment by phb2** [comment]
疲れてしまったので明日以降。

**Comment by u-Bano** [comment]
ひきねこさん乙です
気長にやっていきましょう（私もゆっくり派なので）

**Comment by phb2** [comment]
おつです
そうですね、私はちょっとオーバーワーク気味になる傾向があるので調整します
またーり進行で

**Comment by phb2** [comment]
おわた
https://github.com/hikky-coop/rpg/wiki/Specification
