### ISSUE TITLE
quipmentのタイポ修正

### ISSUE THREAD

**Issue by ghost** [hikky-coop/rpg#13]
[data.xml](https://github.com/hikky-coop/rpg/blob/master/data/data.xml)の`quipment`を`equipment`に修正。

**Comment by u-Bano** [comment]
https://github.com/hikky-coop/rpg/blob/master/game/game.go#L43
game.goの43行目のところも修正する必要がありそうですね

**Comment by phb2** [comment]
あ、ほんとですね
そういえばゲーム開始時に初期装備が反映されないバグがあったような
これのせいですね

**Comment by u-Bano** [comment]
担当します
