### ISSUE TITLE
バージョン番号のブランチをバージョン番号のタグに切り替えてみては

### ISSUE THREAD

**Issue by u-Bano** [hikky-coop/rpg#3]

**Comment by phb2** [comment]
ひきねこ（phb2）がgitのタグ打ちを知らなかったことに由来します＞ブランチ名のバージョン番号

**Comment by phb2** [comment]
タグ打ちでの管理は異論ないけどやり方がわからんから調べる必要あり。

**Comment by u-Bano** [comment]
私がよくやるやり方のコマンドラインですと  
例えばmasterブランチの現在のHEADのコミットにv0.1.0のタグ付けして公開するのは
```bash
$ git checkout master
$ git tag -a v0.1.0
$ git push origin v0.1.0
```
という感じになります

`git tag`ではコミットハッシュを直接指定してタグ付けも出来た気がします

あとGitHub上でもReleasesページでタグ付け(リリース)が出来ます
https://github.com/hikky-coop/rpg/releases
https://github.com/hikky-coop/rpg/tags

**Comment by u-Bano** [comment]
他の人もこのIssueを見てるかもしれないので一応gitが公式で勧めるタグのやり方のページです

https://git-scm.com/book/ja/v2/Git-%E3%81%AE%E5%9F%BA%E6%9C%AC-%E3%82%BF%E3%82%B0

**Comment by phb2** [comment]
プルリクをマージしたブランチmasterにタグv0.11.2を付ける感じがいいですか？
タグ名はvxx.xx.xxが多数派ぽいのでその命名規則でいいと思います。

**Comment by phb2** [comment]
u-Bano氏へ。先に #12 で話し合いをしたいのでよろしくお願いいたします。

**Comment by u-Bano** [comment]
担当します

**Comment by u-Bano** [comment]
完了しました

**Comment by u-Bano** [comment]
> プルリクをマージしたブランチmasterにタグv0.11.2を付ける感じがいいですか？

これやってなかったのでやります

**Comment by u-Bano** [comment]
#20
