### ISSUE TITLE
データセーブ

### ISSUE THREAD

**Issue by u-Bano** [hikky-coop/rpg#7]
セーブデータ
```
ホームディレクトリ/.rpg
```

に保存する

TODO: ゲームごとに保存先のファイルを変える処理を考える
```javascript
{
  "title": "ゲーム名",
  "line-number": 100,
  "status": {
    "hp": 20,
    "str": 10
  }
}
```

**Comment by u-Bano** [comment]
ひきねこ氏によって rpg/src/game/game.go に`Load`と`Save`が実装されてるけど
- 何も処理がされていない
- jsonではなくxmlで処理さている
- ホームディレクトリでない(ホームディレクトリとは`~`のことではない？)

**Comment by phb2** [comment]
u-Bano氏おつです。
Load/Saveは実装していて、一応開発途中で動作確認もしました。完成時にテストしてないので今も動くかどうかはちょっと定かではないです。
Load/Saveの仕様についてはこのスレッドであとで追記します。

**Comment by phb2** [comment]
Load/Saveの仕様の文書化については #11 にマージします。

**Comment by u-Bano** [comment]
wikiとは仕様が変わっていたのですね
仕様が変わった状態で実装済みということでよろしいですか？

**Comment by u-Bano** [comment]
もう一度コードを読みました
実装されてないように見えたのは私の勘違いでしたね・・・どうもすみませんでした
go言語のxmlの取り扱いかたをよく理解してませんでした

**Comment by u-Bano** [comment]
これは実装済みということでよいですね

**Comment by u-Bano** [comment]
勝手に閉じてしまいましたが、閉じたことに問題があるようでしたらこのIssueをReopenします

**Comment by phb2** [comment]
閉じて問題ないと思います。セーブとロードについてはwikiに仕様を追記予定です。たぶん2,3日中には。

**Comment by phb2** [comment]
「閉じて問題ない」というのはひきぷろ氏の言う「えらそう」になるのかな。一応訂正しておきます。s/閉じて問題ない/閉じてくれてありがとうございます/
あと課題ごとのコメントを追いきれていない所があるので、これについても話し合いが必要かも知れないですね。

**Comment by phb2** [comment]
とりあえずそのことは #12 に書いてみますね。

**Comment by u-Bano** [comment]
> 「閉じて問題ない」というのはひきぷろ氏の言う「えらそう」になるのかな。
えらそうとは感じなかったので大丈夫かと思います
